// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(BarlangDbContext))]
    partial class BarlangDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("WebApplication2.Models.barlang", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("hossz")
                        .HasColumnType("INTEGER");

                    b.Property<int>("kiterjedes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("magassag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("melyseg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telepules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Barlangok");
                });
#pragma warning restore 612, 618
        }
    }
}
